### ISSUE TITLE
Unable to load shops menu after spawned on the server

### ISSUE THREAD

**Issue by c0bb1** [RedEM-RP/redemrp_shops#1]
Hello,

I've recently started working on a new RedM server. I installed redemrp_shops and set it up correctly.
However, every time I log into the server my first attempt to use the shops fails.
The camera shows the first product but the menu doesn't show and I cannot exit.

**If I reload the script redemrp_shops, it works perfectly but not on the first attempt.**

The console show this error on my first attempt:
SCRIPT ERROR: @redemrp_shops/client/main.lua:100: attempt to call a nil value (field 'Open')

Thank you for your help in advance!

![image](https://user-images.githubusercontent.com/83042317/115792582-72352300-a3c2-11eb-86d6-e5d49eac88df.png)

**Comment by Ktos93** [comment]
You starting redemrp_menu_base before redemrp_shops? Also you can try add this to shop fxmanifest 
``dependencies {
	'redemrp_menu_base'
}``

**Comment by c0bb1** [comment]
Thank you for your quick reply!

I checked the server.cfg and shops is after menu_base.
Also, put dependencies in the manifest and that **fixed it**!

So definitely that was the solution!

Thank you so much for your help!
